"""init: all tables

Revision ID: 86b04106e66e
Revises: 
Create Date: 2026-07-28 00:21:33.451055
"""
from alembic import op
import sqlalchemy as sa


revision = '86b04106e66e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('failure_clusters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('dominant_surface', sa.String(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_clusters_org_id'), 'failure_clusters', ['org_id'], unique=False)
    op.create_table('robots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('embodiment_type', sa.String(), nullable=False),
    sa.Column('policy_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robots_org_id'), 'robots', ['org_id'], unique=False)
    op.create_table('dataset_exports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('export_uri', sa.String(), nullable=False),
    sa.Column('episode_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['failure_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_exports_cluster_id'), 'dataset_exports', ['cluster_id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('robot_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('source_format', sa.String(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('rlds_uri', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['robot_id'], ['robots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_org_id'), 'episodes', ['org_id'], unique=False)
    op.create_index(op.f('ix_episodes_robot_id'), 'episodes', ['robot_id'], unique=False)
    op.create_table('verification_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('pre_success_rate', sa.Float(), nullable=False),
    sa.Column('post_success_rate', sa.Float(), nullable=False),
    sa.Column('pre_n', sa.Integer(), nullable=False),
    sa.Column('post_n', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['failure_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_runs_cluster_id'), 'verification_runs', ['cluster_id'], unique=False)
    op.create_table('attribution_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attention_map_uri', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attribution_jobs_episode_id'), 'attribution_jobs', ['episode_id'], unique=False)
    op.create_index(op.f('ix_attribution_jobs_org_id'), 'attribution_jobs', ['org_id'], unique=False)
    op.create_table('attributions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('attention_map_uri', sa.String(), nullable=True),
    sa.Column('counterfactual_result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributions_episode_id'), 'attributions', ['episode_id'], unique=True)
    op.create_table('cluster_episodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['failure_clusters.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'episode_id', name='uq_cluster_episode')
    )
    op.create_index(op.f('ix_cluster_episodes_cluster_id'), 'cluster_episodes', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cluster_episodes_episode_id'), 'cluster_episodes', ['episode_id'], unique=False)
    op.create_table('episode_frames',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('t', sa.Integer(), nullable=False),
    sa.Column('action_confidence', sa.Float(), nullable=True),
    sa.Column('contact_force', sa.Float(), nullable=True),
    sa.Column('subgoal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_frames_episode_id'), 'episode_frames', ['episode_id'], unique=False)
    op.create_table('failure_classifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=False),
    sa.Column('surface', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_classifications_episode_id'), 'failure_classifications', ['episode_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failure_classifications_episode_id'), table_name='failure_classifications')
    op.drop_table('failure_classifications')
    op.drop_index(op.f('ix_episode_frames_episode_id'), table_name='episode_frames')
    op.drop_table('episode_frames')
    op.drop_index(op.f('ix_cluster_episodes_episode_id'), table_name='cluster_episodes')
    op.drop_index(op.f('ix_cluster_episodes_cluster_id'), table_name='cluster_episodes')
    op.drop_table('cluster_episodes')
    op.drop_index(op.f('ix_attributions_episode_id'), table_name='attributions')
    op.drop_table('attributions')
    op.drop_index(op.f('ix_attribution_jobs_org_id'), table_name='attribution_jobs')
    op.drop_index(op.f('ix_attribution_jobs_episode_id'), table_name='attribution_jobs')
    op.drop_table('attribution_jobs')
    op.drop_index(op.f('ix_verification_runs_cluster_id'), table_name='verification_runs')
    op.drop_table('verification_runs')
    op.drop_index(op.f('ix_episodes_robot_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_org_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_dataset_exports_cluster_id'), table_name='dataset_exports')
    op.drop_table('dataset_exports')
    op.drop_index(op.f('ix_robots_org_id'), table_name='robots')
    op.drop_table('robots')
    op.drop_index(op.f('ix_failure_clusters_org_id'), table_name='failure_clusters')
    op.drop_table('failure_clusters')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
